name: Feature Request
description: You have an idea for an enhancement within Shiny
title: "[Feature Request]: "
labels: [feature request, unverified]
body:
  - type: markdown
    attributes:
      value: |
        Please note that we are not taking feature requests for Windows or Shiny v2.
  - type: textarea
    attributes:
      label: Summary
      description: Your summary of the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: API Changes
    validations:
      required: true
  - type: textarea
    attributes:
      label: Intended Use Case
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/chiefmonk/sat4.net/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
